version: '3.4'

services:
  server:
    image: sdcserver
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - sdcdata:/var/lib/postgresql/data/

volumes:
  sdcdata:
